src/Entity/Type.php
<?php

namespace App\Entity;

use App\Repository\TypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TypeRepository::class)]
class Type
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\Column]
    private ?float $puissance = null;

    #[ORM\Column(length: 255)]
    private ?string $carburant = null;

    #[ORM\Column(length: 255)]
    private ?string $boite_vitesse = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\OneToMany(mappedBy: 'type', targetEntity: Voiture::class, orphanRemoval: true)]
    private Collection $voitures;

    public function __construct()
    {
        $this->voitures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getPuissance(): ?float
    {
        return $this->puissance;
    }

    public function setPuissance(float $puissance): static
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getCarburant(): ?string
    {
        return $this->carburant;
    }

    public function setCarburant(string $carburant): static
    {
        $this->carburant = $carburant;

        return $this;
    }

    public function getBoiteVitesse(): ?string
    {
        return $this->boite_vitesse;
    }

    public function setBoiteVitesse(string $boite_vitesse): static
    {
        $this->boite_vitesse = $boite_vitesse;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Voiture>
     */
    public function getVoitures(): Collection
    {
        return $this->voitures;
    }

    public function addVoiture(Voiture $voiture): static
    {
        if (!$this->voitures->contains($voiture)) {
            $this->voitures->add($voiture);
            $voiture->setType($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): static
    {
        if ($this->voitures->removeElement($voiture)) {
            // set the owning side to null (unless already changed)
            if ($voiture->getType() === $this) {
                $voiture->setType(null);
            }
        }

        return $this;
    }
}

src/Form/TypeType.php
<?php

namespace App\Form;

use App\Entity\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TypeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('marque',TextType::class,["attr"=>["class"=>"form-control"], "label_attr"=>["class"=>""]])
            ->add('model',TextType::class,["attr"=>["class"=>"form-control"], "label_attr"=>["class"=>""]])
            ->add('puissance',NumberType::class,["attr"=>["class"=>"form-control"], "label_attr"=>["class"=>""]])
            ->add('carburant', ChoiceType::class, [
                'choices' => [
                    'Essence' => 'Essence',
                    'Diesel' => 'Diesel',
                    'Electrique' => 'Electrique',
                ],
                'expanded' => true, // Permet de rendre les cases à cocher au lieu d'un menu déroulant
                'label' => 'Carburant :', // Libellé du champ
                'required' => true, // Champ requis

                "attr"=>[
                    "class"=>"form-control"
                ], 
                
            ])
            ->add('boite_vitesse', ChoiceType::class, [
                'choices' => [
                    'Automatique' => 'Automatique',
                    'Manuelle' => 'Manuelle',
                ],
                'expanded' => true, // Permet de rendre les cases à cocher au lieu d'un menu déroulant
                'label' => 'Boite de vitesse :', // Libellé du champ
                'required' => true, // Champ requis
                "attr"=>[
                    "class"=>"form-control"
                ],
            ])
            ->add('categorie', ChoiceType::class, [
                'choices' => [
                    'Familiale' => 'Familiale',
                    'Luxe' => 'Luxe',
                    'SUV' => 'SUV',
                    'Berline' => 'Berline',
                    'Sport' => 'Sport',
                ],
                'expanded' => true, // Permet de rendre les cases à cocher au lieu d'un menu déroulant
                'label' => 'Catégorie :', // Libellé du champ
                'required' => true, // Champ requis
                "attr"=>[
                    "class"=>"form-control"
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Type::class,
        ]);
    }
}

src/Controller/TypeController.php
<?php

namespace App\Controller;

use App\Entity\Type;
use App\Form\TypeType;
use App\Repository\TypeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/type')]
#[IsGranted('ROLE_ADMIN')]
class TypeController extends AbstractController
{
    #[Route('/', name: 'app_type_index', methods: ['GET'])]
    public function index(TypeRepository $typeRepository): Response
    {
        return $this->render('type/index.html.twig', [
            'types' => $typeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_type_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        
        $type = new Type();
        $form = $this->createForm(TypeType::class, $type);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($type);
            $entityManager->flush();

            return $this->redirectToRoute('app_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('type/new.html.twig', [
            'type' => $type,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_type_show', methods: ['GET'])]
    public function show(Type $type): Response
    {
        return $this->render('type/show.html.twig', [
            'type' => $type,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_type_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Type $type, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TypeType::class, $type);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('type/edit.html.twig', [
            'type' => $type,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_type_delete', methods: ['POST'])]
    public function delete(Request $request, Type $type, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$type->getId(), $request->request->get('_token'))) {
            $entityManager->remove($type);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_type_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/type/_delete_form.html.twig
<form method="post" action="{{ path('app_type_delete', {'id': type.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/type/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/type/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Type{% endblock %}

{% block body %}
<div class="container">

    <h3 class="text-center">Modifier le type de véhicule</h3>
<div class=" d-flex justify-content-sm-center ">

    {{ include('type/_form.html.twig', {'button_label': 'Modifier'}) }}
</div>
<div class="text-center">
    {{ include('type/_delete_form.html.twig') }}
    <a href="{{ path('app_type_index') }}" class="btn btn-info">Retour</a>

    </div>
</div>

{% endblock %}

templates/type/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Type index{% endblock %}

{% block body %}
<div class="container">

    <h1>Type liste</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Marque</th>
                <th>Model</th>
                <th>Puissance</th>
                <th>Carburant</th>
                <th>Boite_vitesse</th>
                <th>Categorie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for type in types %}
            <tr>
                <td>{{ type.id }}</td>
                <td>{{ type.marque }}</td>
                <td>{{ type.model }}</td>
                <td>{{ type.puissance }}</td>
                <td>{{ type.carburant }}</td>
                <td>{{ type.boiteVitesse }}</td>
                <td>{{ type.categorie }}</td>
                <td>
                    <a href="{{ path('app_type_show', {'id': type.id}) }}"class="btn btn-success">Voir</a>
                    <a href="{{ path('app_type_edit', {'id': type.id}) }}"class="btn btn-warning">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucun type</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_type_new') }}" class="btn btn-info">Ajouter un type</a>
    </div>
{% endblock %}

templates/type/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Type{% endblock %}

{% block body %}
<div class="container">

    {# <div class="col-md-6 "> #}
    <h3 class="text-center">Ajouter un type de véhicule</h3>

    {{ include('type/_form.html.twig') }}

    <a href="{{ path('app_type_index') }}" class="btn btn-info">Retour</a>
    </div>
{% endblock %}

templates/type/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Type{% endblock %}

{% block body %}
<div class="container">

    <h1>Type</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ type.id }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ type.marque }}</td>
            </tr>
            <tr>
                <th>Model</th>
                <td>{{ type.model }}</td>
            </tr>
            <tr>
                <th>Puissance</th>
                <td>{{ type.puissance }}</td>
            </tr>
            <tr>
                <th>Carburant</th>
                <td>{{ type.carburant }}</td>
            </tr>
            <tr>
                <th>Boite_vitesse</th>
                <td>{{ type.boiteVitesse }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ type.categorie }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_type_index') }}" class="btn btn-info">Retour</a>

    <a href="{{ path('app_type_edit', {'id': type.id}) }}" class="btn btn-warning">Modifier</a>

    {{ include('type/_delete_form.html.twig') }}
    </div>
{% endblock %}