src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_p = null;

    #[ORM\Column]
    private ?float $note = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $texte = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $auteur = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateP(): ?\DateTimeInterface
    {
        return $this->date_p;
    }

    public function setDateP(\DateTimeInterface $date_p): static
    {
        $this->date_p = $date_p;

        return $this;
    }

    public function getNote(): ?float
    {
        return $this->note;
    }

    public function setNote(float $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): static
    {
        $this->texte = $texte;

        return $this;
    }

    public function getAuteur(): ?Utilisateur
    {
        return $this->auteur;
    }

    public function setAuteur(?Utilisateur $auteur): static
    {
        $this->auteur = $auteur;

        return $this;
    }
}

src/Form/AvisType.php
<?php

namespace App\Form;

use App\Entity\Avis;
use App\Entity\Reservation;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_p', DateType::class, [
                'disabled' => true,
                "attr"=>["class"=>"form-control", ], "label" => "Date :", "label_attr"=>["class"=>""]])
            ->add('note', RangeType::class, [
                "attr"=>["class"=>"form-control"],'attr' => [
                'min' => 1,
                'max' => 5
            ], "label_attr"=>["class"=>""]])
            ->add('texte', TextType::class,[
                "attr"=>["class"=>"form-control"], "label_attr"=>["class"=>""]])
            ->add('auteur', EntityType::class, [
                'disabled' => true,
                'class' => Utilisateur::class,
                'choice_label' => function ($user) {
                    return 'Nom : '.$user->getNom() . ', Prénom : ' . $user->getPrenom() . ', Email : ' . $user->getEmail();
                },
            ])
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Avis::class,
        ]);
    }
}

src/Controller/AvisController.php
<?php

namespace App\Controller;

use App\Entity\Avis;
use App\Entity\Reservation;
use App\Form\AvisType;
use App\Repository\AvisRepository;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/avis')]
class AvisController extends AbstractController
{
    #[Route('/', name: 'app_avis_index', methods: ['GET'])]
    public function index(AvisRepository $avisRepository, EntityManagerInterface $entityManager): Response
    {
        $avis = $entityManager->getRepository(Avis::class)->findAll();
        foreach ($avis as $avi) {
            $aut = $avi->getAuteur();
            $idaut = $aut->getId();
            $nom = $aut->getNom();
            $prenom = $aut->getPrenom();
            
        }
        return $this->render('avis/index.html.twig', [
            'avis' => $avis,
            'idaut' => $idaut,
            'nom' => $nom,
            'prenom' => $prenom,
        ]);
    }

    #[Route('/mesavis', name: 'app_mes_avis', methods: ['GET'])]
    public function mesavis(AvisRepository $avisRepository): Response
    {
        return $this->render('avis/mesavis.html.twig', [
            'avis' => $avisRepository->findBy(
                     ["auteur" => $this->getUser()]
                ),
        ]);
    }

    #[Route('/new', name: 'app_avis_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, ReservationRepository $reservationRepository): Response
    {
        $res = $reservationRepository->findBy(["client" => $this->getUser()]);
        if (!$res) {
            throw $this->createNotFoundException('Vous n\'êtes pas autorisé à laisser un avis car vous n\'avez jamais effectué de réservation.');
        }

        $avi = new Avis();
        $avi->setAuteur($this->getUser());
        $avi->setDateP(new \DateTime('now'));
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avi);
            $entityManager->flush();

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/new.html.twig', [
            'avi' => $avi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avis_show', methods: ['GET'])]
    public function show(Avis $avi): Response
    {
            $aut = $avi->getAuteur();
            $idaut = $aut->getId();
            $nom = $aut->getNom();
            $prenom = $aut->getPrenom();
        return $this->render('avis/show.html.twig', [
            'avi' => $avi,
            'idaut' => $idaut,
            'nom' => $nom,
            'prenom' => $prenom,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_avis_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Avis $avi, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/edit.html.twig', [
            'avi' => $avi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avis_delete', methods: ['POST'])]
    public function delete(Request $request, Avis $avi, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$avi->getId(), $request->request->get('_token'))) {
            $entityManager->remove($avi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/avis/_delete_form.html.twig
<form method="post" action="{{ path('app_avis_delete', {'id': avi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ avi.id) }}">
    <div class='text-center'>
    <button class="btn btn-danger">Supprimer</button>
    </div>
</form>

templates/avis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="text-center">
    <button class="btn">{{ button_label|default('Enregistrer') }}</button> 
    </div>
{{ form_end(form) }}

templates/avis/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Avis{% endblock %}

{% block body %}
<div class="container">
    <h1 class='text-center'>Modifier mon avis</h1>

    {{ include('avis/_form.html.twig', {'button_label': 'Modifier', 'button-class' : 'btn btn-warning'}) }}
    {{ include('avis/_delete_form.html.twig') }}

    <a href="{{ path('app_avis_index') }}">Retour</a>

</div>
{% endblock %}

templates/avis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis index{% endblock %}

{% block body %}
<div class="container">

    <h1 class='text-center'>Avis :</h1>
        <div class="all">
            {% for avi in avis %}
                <div class="unique">
                
                    <p>Avis n°: {{ avi.id }}  {{ avi.dateP ? avi.dateP|date('d-m-Y
                    ') : '' }}</p>
                    <p>{{ nom }} {{prenom}}</p>
                    <div class="stars">
                        {% for i in range(1, avi.note) %}
                            <i class="fas fa-star"></i>
                        {% endfor %}
                    </div>
                    
                    <p>{{ avi.texte }}</p>
                    
                        <a href="{{ path('app_avis_show', {'id': avi.id}) }}" class="btn btn-success">En savoir +</a>
                        {% if app.user %}
                            {% if app.user.id == idaut %}
                                <a href="{{ path('app_avis_edit', {'id': avi.id}) }}"class="btn btn-warning">Modifier</a>
                            {% endif %}
                        {% endif %}
            
                </div>
            {% else %}
                
                    Aucun avis
                
            {% endfor %}

        </div>
        
    {% if app.user %}
    <div class="text-center">
        <a href="{{ path('app_avis_new') }}" class="btn btn-info text-center">Laisser un avis +</a>
    </div>
    {% endif %}
</div>

    
{% endblock %}

templates/avis/mesavis.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis{% endblock %}

{% block body %}
<div class="container">

    <h1> Mes avis :</h1>
    
    {# {{dump(avis)}} #}
    <div class="avis">
            {% for avi in avis %}
                <div class="avi">

                    Avis numéro {{ avi.id }}
                    Date de publication : {{ avi.dateP ? avi.dateP|date('d-m-Y') : '' }}
                    Note : {{ avi.note }}/5
                    Avis : {{ avi.texte }} 
                    <a href="{{ path('app_avis_show', {'id': avi.id}) }}"  class="btn btn-success">+</a>
                    <a href="{{ path('app_avis_edit', {'id': avi.id}) }}"  class="btn btn-warning">Modifier</a>
                </div>
            {% else %}
            
                    <p>no records found</p>
                
            {% endfor %}
        
        </div>
 
    <a href="{{ path('app_avis_index') }}">back to list</a>

    </div>
{% endblock %}

templates/avis/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Avis{% endblock %}

{% block body %}
<div class="container">

    <h1>Laisser un avis </h1>

    {{ include('avis/_form.html.twig') }}

    <a href="{{ path('app_avis_index') }}">Retour</a>
    </div>
{% endblock %}

templates/avis/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis{% endblock %}

{% block body %}
<div class="container">
    <h1>Avis</h1>

    <p>Avis n°: {{ avi.id }}  {{ avi.dateP ? avi.dateP|date('Y-m-d') : '' }}</p>
                    <p>{{ nom }} {{prenom}}</p>
                    <div class="stars">
                        {% for i in range(1, avi.note) %}
                            <i class="fas fa-star"></i>
                        {% endfor %}
                    </div>                    
                    <p>{{ avi.texte }}</p>

    <a href="{{ path('app_avis_index') }}">Retour</a>

    {% if app.user %}
        {% if app.user.id == idaut %}
            <a href="{{ path('app_avis_edit', {'id': avi.id}) }}"class="btn btn-warning">Modifier</a>
            {{ include('avis/_delete_form.html.twig') }}
        {% endif %}
    {% endif %}
</div>
{% endblock %}